### ISSUE TITLE
Update Paper Request

### ISSUE THREAD

**Issue by Ruiyang-061X** [autodriving-heart/ECCV-2024-Papers-Autonomous-Driving#1]
Dear repo author, thanks for your great effort for building this awesome list! I wonder could you kindly merge my ECCV'24 paper on unsupervised 3D object detection into category "9）3D Object Detection | 三维目标检测", or other categories you find appropriate.

The paper info is provided below:

**Approaching Outside: Scaling Unsupervised 3D Object Detection from 2D Scene**

- paper: https://arxiv.org/abs/2407.08569
- code: https://github.com/Ruiyang-061X/LiSe

Thanks again for thoroughly collecting these autonomous driving related papers and building this paper list!

**Comment by loki369loki** [comment]
@Ruiyang-061X 

Dear Ruiyang,

Thank you for your interest in our repository. I have added your ECCV'24 paper "Approaching Outside: Scaling Unsupervised 3D Object Detection from 2D Scene" to the "3D Object Detection" category.

We also invite you to explore our other repositories and hope they will be helpful to you.

Best regards,

Rujia Wang.
